# Generated by Django 5.2 on 2025-06-13 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='documenthistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Document Histories'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='_highlights',
            new_name='highlights',
        ),
        migrations.AddField(
            model_name='document',
            name='document_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='originality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='character_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='originality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='page_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='reading_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='ai_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='character_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='page_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='plagiarism_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='reading_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='ai_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='plagiarism_score',
            field=models.FloatField(default=0.0),
        ),
    ]
